name: test
on:
 workflow_dispatch:
 
jobs:
 static-query:
   runs-on: ubuntu-16.04
   steps:
   - uses: actions/checkout@v2
   - uses: ./
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       query: static.query.yaml
