name: GitHub GraphQL Action
on:
 workflow_dispatch:
 
jobs:
 static-query:
   runs-on: ubuntu-16.04
   steps:
   - uses: helaili/github-graphql-action@2.0.1
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     with:
       query: repository-static.query.yaml
